### ISSUE TITLE
Spurious \clearpage before bibliography

### ISSUE THREAD

**Issue by amunn** [amunn/msu-thesis#26]
Bibliography title appears on its own page when `biblatex` is used.  This suggests that the fix for #21 was either incorrect, or or only needed for per-chapter bibliographies.  More testing needed.

**Comment by amunn** [comment]
Fixed in 8bb797c

**Comment by hcassady** [comment]
I'm still having this issue when using biblatex, although it does seem to be fixed for natbib. 

From my .log file showing that I'm running the most recent version:

```
 *File List*
msu-thesis.cls    2024/06/07 Michigan State University Thesis Class version 4.3
```

A minimum working example with the bug (using the example bib file from the documentation):
```
\documentclass[chapterbib]{msu-thesis}
\listfiles

\usepackage[
	backend=biber,
	style=chem-acs,
	articletitle,
]{biblatex}
\addbibresource{MSU-thesis-testfile.bib}

\begin{document}
\frontmatter
\SingleSpacing
\tableofcontents* 

\mainmatter

\chapter{Introduction}
Intro things.\cite{Munn1999,Chomsky1986}

\printbibliography

\end{document}
```

**Comment by amunn** [comment]
Thanks for the report. I think this version should solve the problem.  btw, it's probably best to load `biblatex` with the `refsection=chapter` package option.

**Comment by hcassady** [comment]
That looks like it's fixed, thanks!!
